name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  API_URL: https://metex-cms-stage.herokuapp.com
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12'
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run deploy
      - name: Run Unit Tests
        run: npm run test:ci
      - name: Run E2E Tests
        run: npm run e2e:ci
